name: Build environment runtime
description: Rootless Docker runtime with Buildkit
runs:
  using: composite
  steps:
    - name: Cache Docker volumes
      uses: actions/cache@v4
      with:
        path: ~/.local/share/docker/volumes
        key: docker-volumes-${{ runner.arch }}-${{ hashFiles('src/**') }}
        restore-keys: docker-volumes-${{ runner.arch }}
    - name: Use Docker in rootless mode
      uses: ScribeMD/rootless-docker@0.2.2
    - name: Set up Buildkit
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: default-load=true
        buildkitd-flags: "" # This does not currently work, see https://github.com/docker/setup-buildx-action/pull/363
        install: true # docker build == docker buildx build
    - name: Expose GitHub runtime # Required for GitHub Actions caching with Buildkit
      uses: crazy-max/ghaction-github-runtime@v3
