# This is a dummy workflow that depends on the Deploy environment,
# it's used to require manual approval on privileged workflow runs

# SECURITY: This can permit PRs from forks to run potentially malicious
# deployments, it's important for these jobs to be configured to always
# require maintainer review and manual approval before running.

on:
  pull_request:
  push:
    branches:
      - master

name: Approve
jobs:
  approve:
    name: Privileged
    environment: approved
    runs-on: ubuntu-latest
    steps:
      - run: echo "Privileged workflows approved"
