on:
  pull_request:
  push:
    branches:
      - master

name: Build
jobs:
  build:
    name: Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          # https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
          fetch-depth: 0
          filter: tree:0
      - name: Use Docker in rootless mode
        uses: ScribeMD/rootless-docker@0.2.2
      - name: Cache Docker volumes
        uses: actions/cache@v4
        with:
          path: ~/.local/share/docker/volumes
          key: docker-volumes-${{ runner.arch }}-${{ hashFiles('**/go.sum') }}
      - name: Run make
        run: make
