on:
  pull_request:
  push:
    branches:
      - master

name: Build
jobs:
  build:
    name: Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
      - name: Run make
        run: make
