on:
  pull_request:
  push:
    branches:
      - master

name: Deploy
jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    permissions:
      packages: write
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Docker in rootless mode
        uses: ScribeMD/rootless-docker@0.2.2
      - name: Cache Docker volumes
        uses: actions/cache@v4
        with:
          path: ~/.local/share/docker/volumes
          key: docker-volumes-${{ runner.arch }}-${{ hashFiles('**/go.sum') }}
      - name: Build and push image
        run: make image-push
      - name: Retrieve image digest
        run: echo "digest=$(make image-digest)" >> "$GITHUB_OUTPUT"
        id: digest
  config:
    name: Configuration
    runs-on: ubuntu-latest
    needs: image
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          path: supernetes
      - name: Check out deployment repository
        uses: actions/checkout@v4
        with:
          repository: supernetes/deploy
          path: deploy
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Prepare deployment repository
        run: >
          cd deploy && git checkout "$BRANCH_NAME" ||
          { git checkout -b "$BRANCH_NAME" && git reset --hard "$(git rev-list --max-parents=0 HEAD)"; }
      - name: Update deployment repository
        run: |
          rsync -a supernetes/deploy/ deploy/ && cd deploy
          kustomize edit set image "${{ needs.image.outputs.digest }}"
          envsubst < ../supernetes/deploy/README.md > README.md
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global push.autoSetupRemote true
      - name: Push a new commit
        run: |
          cd deploy
          git add -A
          git commit -m "release: update controller image to ${{ needs.image.outputs.digest }}"
          git push -f
