name: Deploy image
description: Builds and pushes the controller container image
inputs:
  ghcr-password:
    description: Password for GHCR login
    required: true
outputs:
  digest:
    description: Digest of built image
    value: ${{ steps.digest.outputs.digest }}
runs:
  using: composite
  steps:
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr-password }}
    - name: Set up runtime
      uses: ./supernetes/.github/actions/runtime
    - name: Build and push image
      run: cd supernetes && make image-push
      shell: sh
    - name: Retrieve image digest
      id: digest
      run: cd supernetes && echo "digest=$(make image-digest)" >> "$GITHUB_OUTPUT"
      shell: sh
